
var dotenv = require('dotenv');
dotenv.load();

var fs = require('fs');
var cloudinary = require('cloudinary').v2;


var uploads = {};


console.log( "** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **");

// File upload
cloudinary.uploader.upload('http://i.imgur.com/hDKhVYY.png',{tags:'basic_sample'},function(err,image){
  console.log();
  console.log("** File Upload");
  if (err){ console.warn(err);}
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("Image ID "+image.public_id);
  console.log("Image url "+image.url);
  waitForAllUploads("image",err,image);
});

//file download - geeing image


function waitForAllUploads(id,err,image){
   uploads[id] = image;
   var ids = Object.keys(uploads);
   if (ids.length==6){
     console.log();
     console.log ('**  uploaded all files ('+ids.join(',')+') to cloudinary');
     performTransformations();
   }
 }


